### ISSUE TITLE
Discussion about the Pipeline

### ISSUE THREAD

**Issue by Skeftomilos** [houseofcat/RabbitMQ.Core#12]
Hi HouseCat, Theodor here! I took a quick look at the Pipeline class, and I got the idea that it may be a generic way to build dataflow pipelines, more fluently and less painfully than doing it the standard way. But I am not so sure about this assumption, after noticing that some generally useful configuration options like the `CancellationToken` and the `TaskScheluler` are missing from the library.

Also I am not quite sure what's the point of the async version of the `AddStep`, the `AddAsyncStep`. It seems like it takes a Task created by a previous step, and awaits it. This seems a bit unorthodox. Normally the tasks created by a dataflow block are awaited by the block itself, and this is considered part of the processing. I am talking for example for a `TransformBlock` that is constructed with an async lambda. The lambda is invoked for each input, the resulting task is awaited, and the result of the awaiting is propagated downstream.

**Comment by houseofcat** [comment]
Hey Theodore,

Yes I came across a problem where I need the prior Transform Task<TOut> to become TOut, so I could pass it into the next chained Function. Funcs returning Task<TOut> which is the next TIn and they were all quickly becoming mismatched.

I intend on streamlining that specifically if I can.

Good note about Tokens, when it comes to a custom TaskScheduler pass in, I have been having a hard time finding examples of people doing it with in the last few years. If you have some ideas about this, please send them my way.

I hate doing this to you but I have restructured all my gists, code snippets, and library work to a new Repo.

everything is located https://github.com/houseofcat/Library.

You will see I had non-RabbitMQ things properly separated. You will find piplines under HouseofCat.Workflows.Pipelines project.

You can find a running example in examples\RabbitMQ\ConsumerPipelineMicroservice. It does requiring RabbitMQ installed or running in docker though.

I am archiving this repo now, feel free to continue this discussion over there!
