### ISSUE TITLE
IBasicPublishBatch obsolete method and no alternative

### ISSUE THREAD

**Issue by PseudoCoffee** [houseofcat/RabbitMQ.Core#13]
In the 6.1.0 version IBasicPublishBatch has the following method:
```void Add(string exchange, string routingKey, bool mandatory, IBasicProperties properties, byte[] body)```
which is marked as obsolete and suggest you to use the other method but there is no such method in the interface while the actual implementation:
class BasicPublishBatch : IBasicPublishBatch
does have two Add methods:
```public void Add(string exchange, string routingKey, bool mandatory, IBasicProperties basicProperties, byte[] body)```
and
```public void Add(string exchange, string routingKey, bool mandatory, IBasicProperties basicProperties, ReadOnlyMemory<byte> body)```

Was this intended or was just a minor oversight?

**Comment by houseofcat** [comment]
It seems like you are trying to use the unofficial RabbitMQ client I made?

We aren't using the old unofficial RabbitMQ port I made. They have made remarkable strides in modernizing their client in the last year so it kind of rendered it unnecessary.

https://github.com/houseofcat/RabbitMQ.Core/blob/00a810d919669e8e98f252bb7a36c00f9f830ce2/CookedRabbit.Core/CookedRabbit.Core.csproj#L67

**Comment by PseudoCoffee** [comment]
Sorry, my bad, actually the project we are working on uses the latest version of RabbitMQ.Client by vmware which is 6.2.1, taken using the nuget GUI from visual studio.

Looked again and the interface we use seems to be from this project even though we used RabbitMQ.Client from vmware. 
Your project has an IBasicPublishBatch interface while theirs does not but we downloaded the one provided by vmware and it shows an IBasicPublishBatch, I do not understand anything anymore....

**Comment by houseofcat** [comment]
I think what's happening is that there is an import of CookedRabbit that is using the old library and you have pulled in the VMWare library. And Visual Studio is getting confused?

The latest version of CookedRabbit.Core only needs the VMWare library so if the old one is still installed somewhere, you just have to remove the old one. I apologize for any inconvenience that has caused you.

**Comment by PseudoCoffee** [comment]
My bad, my lack of attention made me confused. Solution is here:
https://github.com/rabbitmq/rabbitmq-dotnet-client/pull/865

TL:DR pre version 7.0(which does not exist yet) of RabbitMQ.Client use the extension class RabbitMQ.Client.BasicPublishBatchExtensions that adds the missing method and after version 7.0 the interface should have the method.
