### ISSUE TITLE
[Question] Message appears stuck in a Queue. It replayed unexpectedly during outage (or long breakpoint).

### ISSUE THREAD

**Issue by volethanh** [houseofcat/RabbitMQ.Core#2]
Hi, I've just tested project SimpleTest and method `await RunParallelExecutionEngineAsync().ConfigureAwait(false);` and I got an error the message is duplicated and the message is still in the queue forever until I stop the application and restart again, then It consume and handle again, at that time it's gone

![image](https://user-images.githubusercontent.com/46510130/82004920-3c55cd80-968e-11ea-9ccc-1d13547a66ba.png)

**Comment by houseofcat** [comment]
The scenario you are describing is a bit complicated.

Are these persisted messages?
Are you acknowledging all messages when you are done?

There are instances depending on the scenario this is perfectly valid. For example, a robust deduplication scenario is where you want to be absolutely sure a message has been processed before proceeding and marking acknowledged. I will run the test client to make sure its nothing obvious or simple.
